### ISSUE TITLE
Add asymmetric parameter 

### ISSUE THREAD

**Issue by patrickpoirier51** [mithi/hexy#3]
First of all a big thanks to @mithi  for this great code 
I do have a different type of hexapod and the servo configuration makes the left and right side asymmetric, so +10 deg on left side makes -10 deg on right side.  Not being a programmer I would kindly request that you consider implementing this new parameter (symetry class ?) so we can expand to a larger hexapod compatibility.

Here is a picture of the ''monster'':
![img_0997](https://cloud.githubusercontent.com/assets/12484190/24985613/5b1e993a-1fc3-11e7-92d1-c0695d3b6d6a.JPG)

**Comment by mithi** [comment]
@patrickpoirier51  Awesome stuff! Alright sure! I'll make a symmetry parameter, 
can I see it move ?? IE can I see a video? :) :)

**Comment by mithi** [comment]
@patrickpoirier51 
Can you explain to me in more detail which parts are moving the wrong way?

for example:
  for each leg, there's the hip, knee, and angle.
  the hip makes it go side ways, while the knee and angle go up and down. 
  So +10 on the left three legs move -10 on the right three legs? Which joint is it? How does it make it move wrongly? Up vs Down or Left vs Right? Thanks!

**Comment by patrickpoirier51** [comment]
@mithi 
Hello Mithi, I will certainly upload a video once it will get its symetry :-)
The more I think about it , it seem more logical to get an additional rotation value (example:  1 for cw and -1 for ccw)  to the  joint_key convention:
    key : (channel, minimum_pulse_length, maximum_pulse_length, rotation) 

joint_properties = {
    'LFH': (0, 248, 398,1), 'LFK': (1, 188, 476,-1), 'LFA': (2, 131, 600,-1), ....

Below are my notes about rotation for my actual robot.
So for a 45 deg command (calibrate.py)  we have:
Left Ankle -45 , Left Knee 45 , Left Hip 45 == Right Hip -45 , Right Knee -45 , Right Ankle 45

![image](https://cloud.githubusercontent.com/assets/12484190/25006340/8e90e6d0-202a-11e7-9e9b-e7be77ff8d64.png)

**Comment by mithi** [comment]
@patrickpoirier51 
Alright, thanks for the added information! 
The image was really helpful, I'm just finishing something else right now, but I'll get back to you within the week once I've finished your requested changes! Thanks!

**Comment by patrickpoirier51** [comment]
@mithi

Hello, I added the direction parameter and it work fine :-)
```
joint_properties = {

    'LFH': (0, 330, 480, -1), 'LFK': (1, 200, 515, -1), 'LFA': (2, 130, 610, 1),
    'RFH': (3, 380, 530, 1), 'RFK': (4, 300, 615, 1), 'RFA': (5, 130, 610, -1),
    'LMH': (6, 320, 470, -1), 'LMK': (7, 251, 531, -1), 'LMA': (8, 130, 610, 1),
    'RMH': (9, 380, 530, 1), 'RMK': (10, 290, 605, 1), 'RMA': (11, 150, 630, -1),
    'LBH': (12, 350, 500, -1), 'LBK': (13, 200, 515, -1), 'LBA': (14, 180, 660, 1),
    'RBH': (15, 350, 500, 1), 'RBK': (16, 300, 615, 1), 'RBA': (17, 130, 610, -1),
    'N': (18, 150, 650, 1)
```
```
class Joint:
    self.channel, self.min_pulse, self.max_pulse, self.direction = joint_properties[jkey]
```
```
def pose:
    pulse = remap((angle * self.direction), (-self.max, self.max), (self.min_pulse, self.max_pulse))
```

**Comment by mithi** [comment]
@patrickpoirier51 awesome! maybe you can submit a pull request, and also looking forward to seeing the video!!!

**Comment by mithi** [comment]
Hi @patrickpoirier51  I've updated the README, let me know if you find it helpful, thanks!
https://github.com/mithi/hexy/blob/master/README.md

**Comment by patrickpoirier51** [comment]
Great , Thanks :-)
