### ISSUE TITLE
Pin assignments for the servos WHERE?

### ISSUE THREAD

**Issue by mano1979** [mithi/hexy#4]
I was wondering what servo should be attached to wich pin. 

Do you have a diagram like for example: Rear Femur Right -- Servocontroller 1 -- pin 2

**Comment by mano1979** [comment]
No matter, i found it allready. But maybe a good idea to put this in the README.md?

**Comment by mithi** [comment]
Hi @mano1979  

Sorry I didn't see this, will update the readme today. 
Good thing you found it. It is located in this file see `joint_properties`  in lines `10-19`
https://github.com/mithi/hexy/blob/master/hexy/robot/core.py

You can use @robottwo's commits (which I haven't merged yet) if it makes it easier for you to configure the pins.. https://github.com/robottwo/hexy/tree/config

**Comment by mithi** [comment]
I'll update the README today thanks

**Comment by mithi** [comment]
Hi @mano1979 
I updated the README, let me know if it's helpful! Thanks!
https://github.com/mithi/hexy/blob/master/README.md
